### ISSUE TITLE
Change name of last wall from "South Wall" to "North Wall"

### ISSUE THREAD

**Issue by markuswust** [NCSU-Libraries/visualization_templates#1]
The name of the last wall in the list should be changed from "South Wall" to "North Wall".

**Comment by mikenutt** [comment]
@markuswust Can you link to the file to which you're referring or make the change yourself?

**Comment by markuswust** [comment]
Don't have write permission, but the file is here:
https://github.com/NCSU-Libraries/visualization_templates/blob/master/after_effects/teaching_and_viz/readme.md

On Wed, Sep 23, 2015 at 10:44 PM, mikenutt notifications@github.com wrote:

> @markuswust https://github.com/markuswust Can you link to the file to
> which you're referring or make the change yourself?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NCSU-Libraries/visualization_templates/issues/1#issuecomment-142787453
> .

## 

Markus Wust
Digital Research and Scholarship Librarian
North Carolina State University Libraries
Raleigh, NC
