### ISSUE TITLE
new server specs

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/visualization_templates#10]
@ejlynema If the server specs have changed for art wall and T&V, can we update this page? https://github.com/NCSU-Libraries/visualization_templates/blob/master/DisplayServerSpecifications.md

**Comment by ejlynema** [comment]
Scott will fix this up. Thanks for the reminder.

**Comment by sdwilli3** [comment]
These are the two entries that were updated:

## Teaching & Visualization Lab
- Dell Precision Tower 7910
- 2x Intel Xeon CPU E5-2680 @ 2.4 GHz (3.3GHz Turbo)
- 128 Gb RAM
- Windows 10 Pro 64
- 512 GB SSD HD (sys)
- 2 x 512 GB SSD HD
- 3x Nvidia K5000 video cards

## Art Wall
- Dell Precision Rack 7910 
- 2x  Intel Xeon CPU E5-2623 v3 @ 3.0 GHz
- 128 Gb RAM
- Windows 10 Pro 64
- 2 x 512 GB SSD HD
- AMD FirePro W9100 video card

**Comment by mikenutt** [comment]
Thanks @sdwilli3. A professor was inquiring about them. 128GB RAM!
