### ISSUE TITLE
Incorrect width

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/visualization_templates#2]
https://github.com/NCSU-Libraries/visualization_templates/blob/master/web/immersion_theater/html_css/immersion_theater_side_panels/immersion_wall_side_panels.css

Width should be 6816px. Not sure if this throws the math off for the panels.

**Comment by WaltGurley** [comment]
Changed width to correct 6816px for both Immersion templates. Doesn't throw off other panels.
