### ISSUE TITLE
Error with PowerPoint slide transitions in Teaching and Viz

### ISSUE THREAD

**Issue by WaltGurley** [NCSU-Libraries/visualization_templates#5]
When using **slide transitions** (not animations) in a PowerPoint presentation in the Teaching and Viz Lab content did not appear in the correct location. **We should advise against the use of slide transitions** when making a PowerPoint presentation for this space. Slide animations work correctly though. :rocket:

**Comment by ghost** [comment]
It might be good to actually add this recommendation into the .ppt itself. See what I did with the Commons Wall Powerpoint: https://github.com/NCSU-Libraries/visualization_templates/tree/master/powerpoint/commons_wall

**Comment by WaltGurley** [comment]
Updated readme.md and .ppt for both T&V powerpoint templates to add: 

> Slide transitions behave unpredictably and should not be used in presentations for this space. Slide animations, however, are appropriate.
