### ISSUE TITLE
Game Lab Chrome resolution?

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/visualization_templates#7]
I just took a screenshot of a full screen Chrome browser in the Game Lab and the resulting image is 7328 px wide X 1720 px tall. [Elsewhere](https://github.com/NCSU-Libraries/visualization_templates/tree/master/_image_templates/game_lab), we say the resolution is 7337 wide. Anyone know the correct resolution for Chrome design?

**Comment by sdwilli3** [comment]
Mike - your screenshot is correct:  7328 x 1720

**Comment by mikenutt** [comment]
Thanks @sdwilli3
